### ISSUE TITLE
Write python wrapper

### ISSUE THREAD

**Issue by secretsauceai** [secretsauceai/mfcc-rust#11]
# Description
To get `mfcc-rust` with python, we will need a wrapper. 
TODO: add in helpful link on how to do that

TODO: write steps needed to close this issue with checkboxes.

# DoD (definition of done)
* passes 4 unit tests
* can run successfully with Python version of Precise (training and inference)

**Comment by skewballfox** [comment]
basic wrapper is already implemented so closing this
