### ISSUE TITLE
Benchmark `SpeechPy` vs. `mfcc-rust`

### ISSUE THREAD

**Issue by secretsauceai** [secretsauceai/mfcc-rust#12]
# Description
Knowing how fast and well `mfcc-rust` performs vs. `SpeechPy` is an important sales point for using this rust version version over the Python version.

- [ ] Define benchmark
- [ ] Run benchmark

# DoD (definition of done)
* Document benchmark method
* Document benchmark (i.e. in a CSV if it has many columns, or just as a small table in the README if it has few columns)

**Comment by skewballfox** [comment]
currently WIP with [mfcc_benchmark](https://github.com/skewballfox/mfcc-benchmark)

**Comment by skewballfox** [comment]
We have the results for initial benchmarking, we matched the speed of speechpy, but librosa was beating us by a wide margin. Will link the benchmark in the readme at some point
